### ISSUE TITLE
64 bit version?

### ISSUE THREAD

**Issue by kf6spf** [univ-of-utah-marriott-library-apple/BHT-UI-Demo#1]
Any chance you have the source for this and can recompile it for macOS Catalina as a 64 bit app?

**Comment by lazymutt** [comment]
I was able to build the [twocanoes](https://bitbucket.org/twocanoes/bighonkingtext/src/master/) version, but that version doesn't seem to match the older version's behavior. At least where my script is concerned.

<img width="1226" alt="Screen Shot 2020-01-08 at 11 30 31 AM" src="https://user-images.githubusercontent.com/3802642/72005305-86273680-320a-11ea-9ecd-b7d48a4eb34c.png">

Send me an [email](mailto:todd.mcdaniel@utah.edu) and I'll get you the version I built.
